CREATE TABLE IF NOT EXISTS `CART` (
    `CARTITEM_COUNT` INT NOT NULL COMMENT '장바구니에 담긴 상품의 수량',
    `ID` VARCHAR(20) NOT NULL COMMENT '사용자 ID',
    `PRODUCT_CODE` INT COMMENT '상품 코드',
    `SUITBOX_CODE` INT COMMENT '맞춤 상품 코드',
    FOREIGN KEY (`ID`) REFERENCES `USER`(`ID`),
    FOREIGN KEY (`PRODUCT_CODE`) REFERENCES `PRODUCT`(`PRODUCT_CODE`),
    FOREIGN KEY (`SUITBOX_CODE`) REFERENCES `SUITBOX`(`SUITBOX_CODE`)
) COMMENT '장바구니';

CREATE TABLE IF NOT EXISTS `ORDER` (
    `ORDER_CODE` INT PRIMARY KEY AUTO_INCREMENT COMMENT '주문 코드',
    `ORDER_STATUS` VARCHAR(1) CHECK(`ORDER_STATUS` IN ('O', 'X', 'C')) NOT NULL COMMENT '주문 상태',
    `ID` VARCHAR(20) NOT NULL COMMENT '사용자 ID',
    `ORDER_RECIPIENT` VARCHAR(5) COMMENT '수령인',
    `ORDER_CONTACT` VARCHAR(11) COMMENT '주문자 연락처',
    `ORDER_ADDRESS` VARCHAR(100) COMMENT '주문자 주소',
    FOREIGN KEY (`ID`) REFERENCES `USER`(`ID`)
)AUTO_INCREMENT = 30003001 COMMENT '주문';
-- 완료 O: Completed
-- 취소 X: Canceled
-- 확정 C: Confirmed Purchase

CREATE TABLE IF NOT EXISTS `PAY` (
    `ORDER_CODE` INT NOT NULL COMMENT '주문 코드',
    `PAY_PRICE` INT NOT NULL COMMENT '결제 가격',
    `PAY_DATE` DATE NOT NULL COMMENT '결제 일자',
    `PAY_STATUS` VARCHAR(1) CHECK(`PAY_STATUS` IN ('O', 'F', 'X')) COMMENT '결제 상태',
    `PAY_METHOD` VARCHAR(7) NOT NULL COMMENT '결제 수단',
    FOREIGN KEY (`ORDER_CODE`) REFERENCES `ORDER`(`ORDER_CODE`)
) COMMENT '결제';
-- 완료 O: Completed
-- 실패 F: Failed
-- 취소 X: Canceled

CREATE TABLE IF NOT EXISTS `REFUND` (
    `REFUND_CODE` INT PRIMARY KEY AUTO_INCREMENT COMMENT '환불 코드',
    `ORDER_CODE` INT NOT NULL COMMENT '주문 코드',
    `REFUND_PRICE` INT NOT NULL COMMENT '환불 가격',
    `REFUND_DATE` DATE NOT NULL COMMENT '환불 일자',
    `REFUND_REASON` VARCHAR(200) COMMENT '환불 이유',
    `REFUND_STATUS` VARCHAR(1) DEFAULT 'R' CHECK( `REFUND_STATUS` IN ('R', 'A', 'D')) COMMENT '환불 상태',
    FOREIGN KEY (`ORDER_CODE`) REFERENCES `ORDER`(`ORDER_CODE`)
)AUTO_INCREMENT = 40004001 COMMENT '환불';
-- 환불요청 R: Refund Request
-- 환불처리중 P: Processing
-- 환불승인 A: Approved
-- 환불거부 D: Denied

CREATE TABLE IF NOT EXISTS `DELIVERY` (
    `ORDER_CODE` INT NOT NULL COMMENT '주문 코드',
    `DELIVERY_CODE` INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '배송 코드',
    `DELIVERY_STATUS` VARCHAR(7) NOT NULL COMMENT '배송 상태',
    FOREIGN KEY (`ORDER_CODE`) REFERENCES `ORDER`(`ORDER_CODE`)
)AUTO_INCREMENT = 50005001 COMMENT '배송';

CREATE TABLE IF NOT EXISTS `DETAIL` (
    `DETAIL_CODE` INT AUTO_INCREMENT PRIMARY KEY COMMENT '상세 주문 코드',
    `DETAIL_STATUS` VARCHAR(1) DEFAULT 'O' CHECK( `DETAIL_STATUS` IN ('O', 'X')) COMMENT '주문 상세 상태',
    `DETAILITEM_COUNT` INT NOT NULL COMMENT '상세 주문 수량',
    `DETAILITEM_PRODUCT_CODE` INT COMMENT '상세 상품 코드',
    `DETAILITEM_SUITBOX_CODE` INT COMMENT '상세 맞춤 상품 코드',
    `ORDER_CODE` INT NOT NULL COMMENT '주문 코드',
    FOREIGN KEY (`DETAILITEM_PRODUCT_CODE`) REFERENCES `PRODUCT`(`PRODUCT_CODE`),
    FOREIGN KEY (`DETAILITEM_SUITBOX_CODE`) REFERENCES `SUITBOX`(`SUITBOX_CODE`),
    FOREIGN KEY (`ORDER_CODE`) REFERENCES `ORDER`(`ORDER_CODE`)
)AUTO_INCREMENT = 60006001 COMMENT '주문상세';
-- 완료 O: Complete
-- 취소 X: Canceled

CREATE TABLE IF NOT EXISTS `IMG` (
	`IMG_CODE` INT AUTO_INCREMENT PRIMARY KEY COMMENT '이미지 코드',
    `IMG_URL` VARCHAR(20) COMMENT '이미지 경로',
    `REFUND_CODE` INT COMMENT '환불 코드',
    FOREIGN KEY (`REFUND_CODE`) REFERENCES `REFUND`(`REFUND_CODE`)
)AUTO_INCREMENT = 70007001 COMMENT '이미지 파일';

INSERT INTO `ORDER` (`ORDER_STATUS`, `ID`)
VALUES
("O", "starry2"),
("O", "junho25"),
("C", "hanan85");

INSERT INTO `PAY`
VALUES
(30003001, 42500, '2024-01-11', 'O', "카카오페이"),
(30003002, 300000, '2023-11-10', 'O', "카카오페이"),
(30003003, 33000, '2024-04-12', 'O', "카카오페이");

INSERT INTO `REFUND` (`ORDER_CODE`, `REFUND_PRICE`, `REFUND_DATE`, `REFUND_REASON`, `REFUND_STATUS`)
VALUES
(30003002, 300000, '2023-11-12', "맛없음, 퍼석퍼석함", DEFAULT);

INSERT INTO `DELIVERY` (ORDER_CODE, DELIVERY_STATUS)
VALUES
(30003001, "배송지연"),
(30003002, "배송취소"),
(30003003, "배송완료");

INSERT INTO `CART` (`CARTITEM_COUNT`, `ID`, `PRODUCT_CODE`)
VALUES	
(3, "starry2", 10001001),
(5, "starry2", 10001003),
(50, "junho25", 10001002),
(6, "hanan85", 10001003);

INSERT INTO `DETAIL` (`DETAIL_STATUS`, `ORDER_CODE`, `DETAILITEM_PRODUCT_CODE`, `DETAILITEM_COUNT`)
VALUES
(DEFAULT, 30003001, 10001001, 3),
(DEFAULT, 30003001, 10001003, 5),
(DEFAULT, 30003002, 10001002, 50),
(DEFAULT, 30003003, 10001003, 6);