DROP TABLE IF EXISTS DETAIL;
DROP TABLE IF EXISTS DELIVERY;
DROP TABLE IF EXISTS IMG;
DROP TABLE IF EXISTS REFUND;
DROP TABLE IF EXISTS PAY;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS CART;

CREATE TABLE IF NOT EXISTS `ORDER` (
    ORDER_CODE INT PRIMARY KEY AUTO_INCREMENT COMMENT '주문 코드',
    ORDER_STATUS VARCHAR(1) CHECK(ORDER_STATUS IN ('O', 'X', 'C')) NOT NULL COMMENT '주문 상태',
    ID VARCHAR(20) NOT NULL COMMENT '사용자 ID',
    ORDER_RECIPIENT VARCHAR(5) COMMENT '수령인',
    ORDER_CONTACT VARCHAR(11) COMMENT '주문자 연락처',
    ORDER_ADDRESS1 VARCHAR(100) COMMENT '주문자 주소1',
    ORDER_ADDRESS2 VARCHAR(100) COMMENT '주문자 주소2',
    ORDER_ADDRESS3 VARCHAR(100) COMMENT '주문자 주소3',
    FOREIGN KEY (ID) REFERENCES USER(ID)
)AUTO_INCREMENT = 30003001 COMMENT '주문';
-- 완료 O: Completed
-- 취소 X: Canceled
-- 확정 C: Confirmed Purchase

drop table cart;
CREATE TABLE IF NOT EXISTS CART (
    CARTITEM_COUNT INT NOT NULL COMMENT '장바구니에 담긴 상품의 수량',
    ID VARCHAR(20) NOT NULL COMMENT '사용자 ID',
    PRODUCT_CODE INT COMMENT '상품 코드',
    #     SUITBOX_CODE INT COMMENT '맞춤 상품 코드',
    FOREIGN KEY (ID) REFERENCES USER(ID),
    FOREIGN KEY (PRODUCT_CODE) REFERENCES tbl_product(PRODUCT_CODE)
    #     FOREIGN KEY (SUITBOX_CODE) REFERENCES SUITBOX(SUITBOX_CODE)
) COMMENT '장바구니';

CREATE TABLE IF NOT EXISTS PAY (
    ORDER_CODE INT NOT NULL COMMENT '주문 코드',
    PAY_PRICE INT NOT NULL COMMENT '결제 가격',
    PAY_DATE DATE NOT NULL COMMENT '결제 일자',
    PAY_STATUS VARCHAR(1) CHECK(PAY_STATUS IN ('O', 'F', 'X')) COMMENT '결제 상태',
    PAY_METHOD VARCHAR(7) NOT NULL COMMENT '결제 수단',
    FOREIGN KEY (ORDER_CODE) REFERENCES `ORDER`(ORDER_CODE)
) COMMENT '결제';
-- 완료 O: Completed
-- 실패 F: Failed
-- 취소 X: Canceled

CREATE TABLE IF NOT EXISTS REFUND (
    REFUND_CODE INT PRIMARY KEY AUTO_INCREMENT COMMENT '환불 코드',
    ORDER_CODE INT NOT NULL COMMENT '주문 코드',
    REFUND_PRICE INT NOT NULL COMMENT '환불 가격',
    REFUND_DATE DATE NOT NULL COMMENT '환불 일자',
    REFUND_REASON VARCHAR(200) COMMENT '환불 이유',
    REFUND_STATUS VARCHAR(1) DEFAULT 'R' CHECK( REFUND_STATUS IN ('R', 'A', 'D')) COMMENT '환불 상태',
    FOREIGN KEY (ORDER_CODE) REFERENCES `ORDER`(ORDER_CODE)
)AUTO_INCREMENT = 40004001 COMMENT '환불';
-- 환불요청 R: Refund Request
-- 환불처리중 P: Processing
-- 환불승인 A: Approved
-- 환불거부 D: Denied

CREATE TABLE IF NOT EXISTS DELIVERY (
    ORDER_CODE INT NOT NULL COMMENT '주문 코드',
    DELIVERY_CODE INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '배송 코드',
    DELIVERY_STATUS VARCHAR(7) NOT NULL COMMENT '배송 상태',
    FOREIGN KEY (ORDER_CODE) REFERENCES `ORDER`(ORDER_CODE)
)AUTO_INCREMENT = 50005001 COMMENT '배송';

CREATE TABLE IF NOT EXISTS DETAIL (
    DETAIL_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '상세 주문 코드',
    DETAIL_STATUS VARCHAR(1) DEFAULT 'O' CHECK( DETAIL_STATUS IN ('O', 'X')) COMMENT '주문 상세 상태',
    DETAILITEM_COUNT INT NOT NULL COMMENT '상세 주문 수량',
    DETAILITEM_PRODUCT_CODE INT COMMENT '상세 상품 코드',
    DETAILITEM_SUITBOX_CODE INT COMMENT '상세 맞춤 상품 코드',
    ORDER_CODE INT NOT NULL COMMENT '주문 코드',
    FOREIGN KEY (DETAILITEM_PRODUCT_CODE) REFERENCES tbl_product(PRODUCT_CODE),
    #     FOREIGN KEY (DETAILITEM_SUITBOX_CODE) REFERENCES SUITBOX(SUITBOX_CODE),
    FOREIGN KEY (ORDER_CODE) REFERENCES `ORDER`(ORDER_CODE)
)AUTO_INCREMENT = 60006001 COMMENT '주문상세';
-- 완료 O: Complete
-- 취소 X: Canceled

CREATE TABLE IF NOT EXISTS IMG (
    IMG_CODE INT AUTO_INCREMENT PRIMARY KEY COMMENT '이미지 코드',
    IMG_URL VARCHAR(20) COMMENT '이미지 경로',
    REFUND_CODE INT COMMENT '환불 코드',
    IMG_CATEGORY INT NOT NULL,
    FOREIGN KEY (REFUND_CODE) REFERENCES REFUND(REFUND_CODE)
)AUTO_INCREMENT = 70007001 COMMENT '이미지 파일';
-- 구현중