USE DOSIRAK;
DROP TABLE IF EXISTS USER CASCADE;

CREATE TABLE IF NOT EXISTS USER (
                                    ID VARCHAR(20) UNIQUE NOT NULL COMMENT '회원아이디',
    NAME VARCHAR(5) NOT NULL COMMENT '이름',
    BIRTH DATE NOT NULL COMMENT '생년월일',
    GENDER CHAR NOT NULL COMMENT '성별',
    PHONE VARCHAR(20) NOT NULL COMMENT '휴대폰번호',
    EMAIL VARCHAR(50) NOT NULL COMMENT '이메일',
    ADDRESS1 VARCHAR(50) COMMENT '주소1',
    ADDRESS2 VARCHAR(50) COMMENT '주소2',
    ADDRESS3 VARCHAR(50) COMMENT '주소3',
    AGREE VARCHAR(10) COMMENT '마케팅동의',
    PWD VARCHAR(50) NOT NULL COMMENT '비밀번호',
    JOINDATE DATE NOT NULL COMMENT '가입날짜',
    WITHDRAWAL BOOLEAN NOT NULL COMMENT '탈퇴여부' DEFAULT FALSE,
    ROLE VARCHAR(50) NOT NULL COMMENT '사용자구분' DEFAULT 'USER'
    ) ENGINE=INNODB COMMENT '회원';

INSERT INTO USER VALUES ('starry2', '김성우', '1993-07-15', '남', '01012345678', 'starry2@gmail.com', '06133', '서울 강남구 테헤란로 123' , '101호', '문자', 'starry2', '2024-04-21', FALSE, 'USER');
INSERT INTO USER VALUES ('junho25', '이준호', '1988-05-02', '남', '01098765432', 'junho25@naver.com', '16546', '경기 수원시 영통구 매탄로 69', '201호', '문자, 이메일', 'junho25', '2024-04-30', FALSE, 'USER');

select * from USER;