CREATE DATABASE DOSIRAK;
GRANT ALL PRIVILEGES ON DOSIRAK.* TO 'ohgiraffers'@'%';

CREATE DATABASE dosirakdb;

CREATE USER 'dosirak'@'%' IDENTIFIED BY 'dosirak';

GRANT ALL PRIVILEGES ON dosirakdb.* TO 'dosirak'@'%';